# Generated by Django 4.1.1 on 2022-10-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_death",
            field=models.DateField(blank=True, null=True, verbose_name="date of death"),
        ),
        migrations.AlterField(
            model_name="author",
            name="display_image",
            field=models.ImageField(
                default="display-img.png",
                upload_to="authors-image/",
                verbose_name="display image",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="year_published",
            field=models.DateField(
                blank=True, null=True, verbose_name="year published"
            ),
        ),
    ]
