# Generated by Django 4.1.1 on 2023-02-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_author_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
        migrations.AddField(
            model_name="genre",
            name="description",
            field=models.TextField(
                default="***No description***", verbose_name="description"
            ),
        ),
    ]
