# Generated by Django 4.1.1 on 2023-02-05 09:02

from django.db import migrations, models
import modules.store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_author_verified_genre_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="genre_image",
            field=models.ImageField(
                default="genre.png",
                upload_to=modules.store.models.book_genre_covers_directory_path,
                verbose_name="genre image",
            ),
        ),
    ]
