# Generated by Django 4.1.1 on 2023-02-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_genre_genre_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratings",
            name="flag",
            field=models.BooleanField(default=False, verbose_name="flag"),
        ),
    ]
