# Generated by Django 2.2.6 on 2019-12-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191201_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='book_cover'),
        ),
    ]
